### ISSUE TITLE
Installing Using pip failed due to Could not find a version that satisfies the requirement GoogleAppEngineCloudStorageClient==trunk requirement

### ISSUE THREAD

**Issue by suarezjulian** [masci/django-appengine-toolkit#2]
Insallation using pip fails with this error:

Could not find a version that satisfies the requirement GoogleAppEngineCloudStorageClient==trunk (from django-appengine-toolkit) (from versions: 1.7.3.1, 1.8.3.1, 1.9.0.0)

**Comment by masci** [comment]
It's fixed in master, going to bake a bugfix release

**Comment by masci** [comment]
0.2.1 just released, thanks for reporting
